config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "urls#index"
  get "/urls" => 'urls#new'
  post "/urls" => 'urls#create'
  get "/:look_up" => 'urls#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/button.rb
class Button < ApplicationRecord
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original_url, :look_up, presence: true
  validates_uniqueness_of :look_up
  validate :original_url_format

  def original_url_format
  	uri = URI.parse(original_url || "")
  	if uri.host.nil?
  	 errors.add(:original_url, "Invalid Format")
  	end
  end

  def shortened_url
  	"http://localhost:3000/#{look_up}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all
    @button_click = Button.first.clicks
  end

  def new
    @url = Url.new
  end

  def show
    @url = Url.find_by(look_up: params[:look_up])
    redirect_to @url.original_url
  end

  def create
    click
    shortener = Shortener.new(url_params[:original_url])
    @url = shortener.generate_short_link

    if @url.persisted?
      respond_to :js
    else
      render 'error.js.erb'
    end
  end

  def click
    @button = Button.find(1)
    @newcount = @button.clicks + 1
    Button.find(1).update_attributes(:clicks => @newcount)
  end

  private
  def url_params
    params.require(:url).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_url.html.erb
<div class="footer">
  <div class="card-body">
    <div class="alert alert-success">
      <b>Shortened URL  </b><%= url %>
     </div>
   </div>
</div>

app/views/urls/create.js.erb
var element = document.getElementById('short-link');

var html = "<%= j render 'url', url: @url.shortened_url %>";
element.innerHTML = html

app/views/urls/error.js.erb
var message = "<%= @url.errors.full_messages.join(" . ") << " ." %>";


var element = document.getElementById('short-link');
element.innerHTML = message;

app/views/urls/index.html.erb
<div class="container ">
    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">Wanna Shorten Url</h5>
            <a href="<%= urls_path %>" class="btn btn-primary">Click Here</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="p-5">
        <h5>Total Click
            <%= @button_click%>
        </h5>
        <% @urls.each do |url| %>
        <div class="card">
            <div class="card-body">
                <h6>Original Url :-
                    <%= url.original_url %>
                </h6>
                <h6>Shortened :-
                    <%= url.shortened_url %>
                </h6>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/urls/new.html.erb
<div class = "cointainer px-4 ml-5 mt-3">
  <div class="btn btn-primary float-right"> 
    <%= link_to "Back", root_path, :class => "btn" %>
  </div> 
</div>


<div class="container">
  <div class="p-5">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @url, remote: true do |form| %>
        <h5><div class="card-title">Enter a URL to be shorten </h5>
          <%= form.text_field :original_url, class: "form-control", placeholder: "Enter url ---" %>
          <%= form.submit 'Shorten Url', class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
      <div id="short-link">
       </div>
    </div>
  </div> 
</div>